### PR TITLE
Shell completion for executables in bin/

### PR DESCRIPTION
**Pull request by sebix**
It was so annoying now so I quickly coded some bash completion functions for ctl and dump

Please test it :)

### CODE REVIEW

**Comment by SYNchroACK** [comment]
@sebix nice feature! I reviewed on Ubuntu and CentOS servers and it works perfectly!


I would like to propose some improvements:


* Creation of a README.md file under the directory 'contrib/bash-completion/README.md' with the following content:

```
# Bash Completion for IntelMQ

Bash completion for IntelMQ can be set up with the following procedures:

## Dependencies

### Ubuntu 14.04 / Debian 8

'''
apt-get install bash-completion jq
'''

### CentOS 7

'''
yum install bash-completion jq
'''

## Install

1. Copy intelmq.sh from repository to '/etc/bash_completion.d/'
2. Logout and login to be able to use the 'intelmqctl' with bash completion.
```

* Add a sub-section 'Bash completion' on 'User-Guide.md', under the section 'Utilities > Management > Command-line interface: intelmqctl' with the following content:

```
#### Bash completion

To enable bash completion on `intelmqctl` in order to help you run the commands in an easy manner, follow the installation process [here](../contrib/bash-completion/README.md).
```

**Comment by ondj** [comment]
I like it too, but maybe it will be better to get a list of bots and queues from `intelmqctl` command and not directly from JSON files.

**Comment by wagner-certat** [comment]
Documentation: added.

> Rename the intelmq.sh file to intelmqctl.sh

Why? It also completes for intelmqdump


> I like it too, but maybe it will be better to get a list of bots and queues from intelmqctl command and not directly from JSON files.

I avoided calling the tool as it has a lot of file- and library dependencies while jq is very lightweight.

**Comment by SYNchroACK** [comment]
> Documentation: added.
> 

Perfect!

> Rename the intelmq.sh file to intelmqctl.sh
> Why? It also completes for intelmqdump
> 

Good justification, ignore my comment.

> I like it too, but maybe it will be better to get a list of bots and queues from intelmqctl command and not directly from JSON files.
> I avoided calling the tool as it has a lot of file- and library dependencies while jq is very lightweight.

Ok, fair enough.

**From my side, ready to merge**

**Pull request merged**
