### PR TITLE
Shadowserver config fixups

### PR DESCRIPTION
**Pull request by sebix**
Rebased from #735

### CODE REVIEW

**Comment by dmth** [comment]
Thanks for giving this a fresh start.

Questions so far:
 1. Do you want to stick to the approach, that no `feed.name` is set by the parser? Have we agreed that this should always be done by a collector as a user-configurable parameter? See https://github.com/certtools/intelmq/issues/725 for a start of this discussion
 2. Do we want to keep the `feedname` <-> `feed.name` ambiguity or can we resolve this somehow? For instance by resolving `feed.name` from the report send by the collector if no explicit `feedname` is present (see line https://github.com/certtools/intelmq/blob/56d18d31b27185cd247a85addb907af7581f048f/intelmq/bots/parsers/shadowserver/parser.py#L31 where the correct parser configuration is discovered by using this parameter)
 3. The Overwrite / Override Change is not applied to this PR, might be reasonable to do.

**Comment by dmth** [comment]
@sebix I've no objections for this PR, I think we can deal with the alterations which happened here.

I want to get this one going, in order to be able of merging the other parser configurations contributed  in https://github.com/certtools/intelmq/pull/748

The part where `feed.code` is set should be removed now.
https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/shadowserver/parser.py#L162


What Intevation needs to do for their setup to keep this working afterwards:
 - Ensure Override / Overwrite is set to "True" in order to set the correct `feed.name` by the parser to `self.parameters.feedname`

**Comment by dmth** [comment]
@sebix @aaronkaplan When will this PR be merged?

**Comment by sebix** [comment]
> Do you want to stick to the approach, that no feed.name is set by the parser? Have we agreed that this should always be done by a collector as a user-configurable parameter? See #725 for a start of this discussion

> Do we want to keep the feedname <-> feed.name ambiguity or can we resolve this somehow? For instance by resolving feed.name from the report send by the collector if no explicit feedname is present (see line https://github.com/certtools/intelmq/blob/56d18d31b27185cd247a85addb907af7581f048f/intelmq/bots/parsers/shadowserver/parser.py#L31 where the correct parser configuration is discovered by using this parameter)

I think @aaronkaplan can best answer this.

The overwrite/override PR has been merged just now.

**Comment by dmth** [comment]
Hi,

The questions I mentioned above should not stop you from merging this PR.

Nevertheless
> The part where feed.code is set should be removed now.
> https://github.com/certtools/intelmq/blob/master/intelmq/bots/parsers/shadowserver/parser.py#L162

might need another look. The code is superfluos right now.

**Comment by sykaeh** [comment]
I would really appreciate it if this PR was merged soon as well. There seem to be a lot of open PR with regards to the Shadowserver parser.

1. A compromise might be to set the `feed.name` if there currently is no `feed.name`. 

2. I think using the `feed.name` from the report if no feedname parameter is specified is a great idea. That why every organization can decide themselves whether they want to specify the feed name in the collector or the parser. However this would mean moving the selection of the correct config from the `init()` block to the `parse()` block.

**Comment by dmth** [comment]
@sebix Thanks for merging this!

> However this would mean moving the selection of the correct config from the init() block to the parse() block. 

If we can assumpt, that every report contains the same feed.name and it does not change between reports, we only need to lookup the config once.
It might be tested if the `feed.name` from the report, differs from the `feed.name` that was received from the previous report. If yes: Load a new Config, if no: Stick to the previos config.  This would enable ONE Parser for different collectors.

I think we can be capable of providing both approaches.

**Pull request merged**
