### PR TITLE
WIP: AMQP support

### PR DESCRIPTION
**Pull request by wagner-certat**
AMQP support is feature-complete, needs still to be tested on development machines and some unittests are needed.

 - [x] All features for `intelmqctl`
 - [x] Unit tests
 - [x] Documentation
 - [x] real world tests
 - [x] clearing queues
 - [x] paths
 - [x] lazy queues

### CODE REVIEW

**Comment by wagner-certat** [comment]
There are speed problems and problems with unacked messages. Postponing this

**Comment by wagner-certat** [comment]
```
  File "/home/sebastianw/intelmq/intelmq/lib/pipeline.py", line 293, in __init__
    raise exceptions.ConfigurationError("To use AMQP you must install the 'pika' library.")
TypeError: __init__() missing 1 required positional argument: 'argument'
```

**Comment by SYNchroACK** [comment]
@wagner-certat what do you think about using "lazy queues" feature?
https://www.rabbitmq.com/lazy-queues.html

I think is something that we miss a lot due a lot of messages that stuck on experts (like cymru-whois, gethostbyname and deduplicator).

**Comment by SYNchroACK** [comment]
```
$ intelmqctl list queues
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 174, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/lib/python3/dist-packages/redis/_compat.py", line 79, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 493, in connect
    self.on_connect()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 567, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 191, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 174, in _read_from_socket
    data = recv(self._sock, socket_read_size)
  File "/usr/lib/python3/dist-packages/redis/_compat.py", line 79, in recv
    return sock.recv(*args, **kwargs)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dev_intelmq/intelmq/lib/pipeline.py", line 204, in count_queued_messages
    queue_dict[queue] = self.pipe.llen(queue)
  File "/usr/lib/python3/dist-packages/redis/client.py", line 1325, in llen
    return self.execute_command('LLEN', name)
  File "/usr/lib/python3/dist-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 493, in connect
    self.on_connect()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 567, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 284, in read_response
    response = self._buffer.readline()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 216, in readline
    self._read_from_socket()
  File "/usr/lib/python3/dist-packages/redis/connection.py", line 191, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/intelmqctl", line 11, in <module>
    load_entry_point('intelmq', 'console_scripts', 'intelmqctl')()
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 1178, in main
    return x.run()
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 598, in run
    retval, results = args.func(**args_dict)
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 758, in list
    return self.list_queues()
  File "/opt/dev_intelmq/intelmq/bin/intelmqctl.py", line 832, in list_queues
    counters = pipeline.count_queued_messages(*all_queues)
  File "/opt/dev_intelmq/intelmq/lib/pipeline.py", line 206, in count_queued_messages
    raise exceptions.PipelineError(exc)
intelmq.lib.exceptions.PipelineError: pipeline failed - ConnectionError("Error while reading from socket: (104, 'Connection reset by peer')",)
```

**Comment by wagner-certat** [comment]
Ad lazy queues: Thanks for the pointer, definitely

> On this line (https://github.com/certtools/intelmq/blob/dev-amqp/intelmq/lib/pipeline.py#L39) it seems that we need to add .title()

yes, thanks.

> Also, on this line (https://github.com/certtools/intelmq/blob/dev-amqp/intelmq/lib/pipeline.py#L41) it seems now we have three broker options, and I guess the one on line 41 will be required by intelmqctl

What do you mean?

**Pull request merged**
