### PR TITLE
Modify bot: Add an additional example config

### PR DESCRIPTION
**Pull request by gsiv**
I'm not crazy about the file name but here it goes. See also PR #575.

### CODE REVIEW

**Comment by aaronkaplan** [comment]
thanks!

**Comment by sebix** [comment]
Is this just an extended version of the existing example?

**Comment by gsiv** [comment]
On Thu, Jul 21, 2016 at 08:49:35AM -0700, Sebastian wrote:
> Is this just an extended version of the existing example?

Yeah, pretty much, I guess.  Not having written it I don't know for
for sure, though.  @dmth probably knows the details.

**Comment by dmth** [comment]
yes, it is. A lot of stuff is not required for our usecase.

**Pull request merged**
