### PR TITLE
Added authentication to mongoDB output

### PR DESCRIPTION
**Pull request by vince-nayal**
Hello,

With this PR, i'd like to add the authentication option to mongoDB ouput bot.

It should not have any impact on config not needing auth.

Regards,

### CODE REVIEW

**Comment by wagner-certat** [comment]
I read the documentation concerning authentication in mongodb. There's always a separate database for users, called `admin`. To authenticate one must first use this DB, authenticate there, and then switch to the actual database.


Did I undertand this correctly?

**Comment by vince-nayal** [comment]
From my understanding and my recent use of auth in mongoDB, i don't think so.
You have both **Authentication** and **Authorization**

- **Authentication** is per db and simply forbids anonymous access to the db
- **Authorization** grants roles to the db users (R, RW, userAdmin). it can be per db or mongo wide
The admin db is where you define roles for all db (eg: dbAdminAnyDatabase)

ref : [mongo doc (2.4)](https://docs.mongodb.com/v2.4/core/access-control/)

**Comment by wagner-certat** [comment]
Thanks, pushed (slightly rebased) to master, added default values and even [tests](f4c8297efe2a503076194cfab7c80ebf48993ef4).

**Comment by vince-nayal** [comment]
Thanks !

**Pull request closed without merging**
