### PR TITLE
CA trusted certificate support

### PR DESCRIPTION
**Pull request by tomas321**

### CODE REVIEW

**Comment by tomas321** [comment]
Thank you for the recommendations, I have applied the changes to the branch.

**Comment by wagner-certat** [comment]
Thanks.

I expect that I can't review/merge it before the Christmas holidays unfortunately :(

**Comment by tomas321** [comment]
That's okay. It can wait.

**Comment by wagner-certat** [comment]
I merged the relevant 3 commits.

Seems like I mixed `ssl_ca_certificate` and  `ssl_ca_certs` in my comment above. I wanted to say that `ssl_ca_certificate` is best as it is in line with the convention and most self-explaining.
You used `ca_file` in the bot and documented for `ssl_ca_cert`. Anyway, I now harmonized this to `ssl_ca_certificate` everywhere and documented it. I hope this is now clearly documented and the name is telling.
f1725cfe4

**Pull request closed without merging**
