### PR TITLE
[ENH] extract malware name from fraunhofer dga feed

### PR DESCRIPTION
**Pull request by navtej**
Adds the malware name to the dga feed domain.

### CODE REVIEW

**Comment by wagner-certat** [comment]
I asked upstream if this is a good solution and it's guaranteed to work.

**Comment by wagner-certat** [comment]
> I asked upstream if this is a good solution and it's guaranteed to work.

According to upstream it is guaranteed that everything before the first underscore can be treated as malware name.

**Comment by navtej** [comment]
I have sqashed the commits but i cant push something is wrong with upstream, could you please do it? Thanks.

**Comment by wagner-certat** [comment]
Done in 0eb770cc1ca7f146974afd45a7fa8653c15171bd

Added an additional note in 48760afcca5e486f22a7304d79898b1401d6ec2e

**Pull request closed without merging**
