### PR TITLE
FIX: Adds somewhat dirty fix for #1765.

### LINKED ISSUE #1765: Crash loop on event with ASN = 0
Every now and then there appears an event with `source.asn = 0` in our pipeline. Whenever a bot receives such message, it throws an exception InvalidValue. The bot then gets stuck in a loop between this exception and PipelineError exception.

The `defaults` configuration:
```
  "error_dump_message": true,
  "error_log_exception": true,
  "error_log_message": true,
  "error_max_retries": 3,
  "error_procedure": "pass",
  "error_retry_delay": 15,
```

Log (from `intelmqctl run`):
```
abusix-expert-cz: Bot has found a problem.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/intelmq/lib/bot.py", line 269, in start
    self.process()
  File "/usr/local/lib/python3.8/dist-packages/intelmq/bots/experts/abusix/expert.py", line 26, in process
    event = self.receive_message()
  File "/usr/local/lib/python3.8/dist-packages/intelmq/lib/bot.py", line 606, in receive_message
    self.__current_message = libmessage.MessageFactory.unserialize(message,
  File "/usr/local/lib/python3.8/dist-packages/intelmq/lib/message.py", line 72, in unserialize
    return MessageFactory.from_dict(message, harmonization=harmonization,
  File "/usr/local/lib/python3.8/dist-packages/intelmq/lib/message.py", line 54, in from_dict
    return class_reference(message, auto=True, harmonization=harmonization)
  File "/usr/local/lib/python3.8/dist-packages/intelmq/lib/message.py", line 539, in __init__
    super().__init__(template, auto, harmonization)
  File "/usr/local/lib/python3.8/dist-packages/intelmq/lib/message.py", line 127, in __init__
    self.add(key, value, sanitize=True)
  File "/usr/local/lib/python3.8/dist-packages/intelmq/lib/message.py", line 249, in add
    raise exceptions.InvalidValue(key, old_value)
intelmq.lib.exceptions.InvalidValue: invalid value 0 (<class 'int'>) for key 'source.asn'
abusix-expert-cz: Current Message(event): None.
abusix-expert-cz: Bot will continue in 15 seconds.
abusix-expert-cz: Pipeline failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/intelmq/lib/bot.py", line 269, in start
    self.process()
  File "/usr/local/lib/python3.8/dist-packages/intelmq/bots/experts/abusix/expert.py", line 26, in process
    event = self.receive_message()
  File "/usr/local/lib/python3.8/dist-packages/intelmq/lib/bot.py", line 591, in receive_message
    message = self.__source_pipeline.receive()
  File "/usr/local/lib/python3.8/dist-packages/intelmq/lib/pipeline.py", line 122, in receive
    raise exceptions.PipelineError("There's already a message, first "
intelmq.lib.exceptions.PipelineError: pipeline failed - "There's already a message, first acknowledge the existing one."
abusix-expert-cz: Bot will continue in 15 seconds.
```

The bot keeps throwing these two exceptions and never stops. Expected behavior would be to follow `defaults.conf`, try it three times (even better would be to try just once for this kind of exception because the problem is obviously not going to go away) and then just dump the message and continue processing another one. However the message is never dumped (not to dump file nor the log - see the log line `Current Message(event): None.`) because it is never even loaded.

Currently the InvalidValue exceptions gets caught by a generic Exception handler:
https://github.com/certtools/intelmq/blob/b7ba19ceaba219e6aa87a37784164dbdf0b3e680/intelmq/lib/bot.py#L329-L353

I believe it should be better handled in a similar fashion to DecodingError:
https://github.com/certtools/intelmq/blob/b7ba19ceaba219e6aa87a37784164dbdf0b3e680/intelmq/lib/bot.py#L320-L327

### PR DESCRIPTION
**Pull request by gethvi**
# Description

This fixes #1765.

It adds dump object to InvalidValue exception so that the code below has some meaningful data to dump and can just move on (the last two lines that acknowledge the message if there is a message to dump).

https://github.com/certtools/intelmq/blob/b7ba19ceaba219e6aa87a37784164dbdf0b3e680/intelmq/lib/bot.py#L372-L384

### CODE REVIEW

**Comment by wagner-certat** [comment]
See https://github.com/gethvi/intelmq/pull/1 for an attempted test case checking the new behaviour. But it currently fails with 
```
test-bot: ERROR: Bot has found a problem.
Traceback (most recent call last):
  File "/home/sebastianw/dev/intelmq/intelmq/lib/bot.py", line 307, in start
    self.process()
  File "/home/sebastianw/dev/intelmq/intelmq/lib/bot.py", line 1045, in process
    report = self.receive_message()
  File "/home/sebastianw/dev/intelmq/intelmq/lib/bot.py", line 657, in receive_message
    self.__current_message = libmessage.MessageFactory.unserialize(message,
  File "/home/sebastianw/dev/intelmq/intelmq/lib/message.py", line 72, in unserialize
    return MessageFactory.from_dict(message, harmonization=harmonization,
  File "/home/sebastianw/dev/intelmq/intelmq/lib/message.py", line 54, in from_dict
    return class_reference(message, auto=True, harmonization=harmonization)
  File "/home/sebastianw/dev/intelmq/intelmq/lib/message.py", line 539, in __init__
    super().__init__(template, auto, harmonization)
  File "/home/sebastianw/dev/intelmq/intelmq/lib/message.py", line 127, in __init__
    self.add(key, value, sanitize=True)
  File "/home/sebastianw/dev/intelmq/intelmq/lib/message.py", line 249, in add
    raise exceptions.InvalidValue(key, old_value, object=bytes(json.dumps(self.iterable), 'utf-8'))
  File "/usr/lib64/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict_items is not JSON serializable
test-bot: DEBUG: Testing environment detected, returning now.
test-bot: DEBUG: Disconnected from source pipeline.
test-bot: DEBUG: Disconnected from destination pipeline.
test-bot: INFO: Bot stopped.
```
Some other tests fail as well

**Comment by gethvi** [comment]
Thanks for the tests!

**Comment by schacht-certat** [comment]
It would be great if you could squash those commits into one

**Comment by wagner-certat** [comment]
> It would be great if you could squash those commits into one

Or two, as one of them is from me :P

**Comment by gethvi** [comment]
Squashed into two. :-)

**Review by wagner-certat — APPROVED** [review]
fine for me

**Review by schacht-certat — APPROVED** [review]
LGTM

**Pull request merged**
