### PR TITLE
collector-http autounzip

### PR DESCRIPTION
**Pull request by robcza**
Should there be a zip archive downloaded by the collector, unzip all files and create a report for each of them and log the unzipped file names.

### CODE REVIEW

**Comment by robcza** [comment]
@sebix is the current solution with imports proper and valid for both python2 and python3? Because if yes, I would leave it as it is.

**Comment by sebix** [comment]
There's no `StringIO` or `cStringIO` module in current Python :) They only exist in old legacy Python.

**Comment by robcza** [comment]
seems a valid reason :) will elaborate further, do not merge

**Comment by robcza** [comment]
Seems ok to me now. Works smoothly, tested against both - zip and plaintext files. 
Mergeable from my point of view.

**Comment by sebix** [comment]
Thanks, also tested successfully.

**Pull request merged**
