### PR TITLE
Fix for missing user_agent parameter

### PR DESCRIPTION
**Pull request by robcza**
simple check, whether user_agent parameter exists

### CODE REVIEW

**Comment by SYNchroACK** [comment]
Sorry @robcza but We have been discussing this issue and the temporary solution is to put the parameter 'user_agent: null' in defaults.conf. The solution that you propose it not correct because for each parameter in the same situation we will have to add in all bots that if, which cannot be. So, the solution is to define the default value in some generic place like defaults.conf. The best solution will be created in some days, because the configurations need some improvements. I hope you dont mind. 

Check the solution:
3fe60694aadb7983959b2383123bcd701973263e
35f5aad4992ffd041d84c0d41226129ec0882aa5
d521093bef70afe9958179ed4fce36362e91ef96

**Comment by robcza** [comment]
I don't, seems legit :)

**Comment by SYNchroACK** [comment]
;)

**Comment by SYNchroACK** [comment]
If you have time, test the current solution. ;) I dint have time to do it... :(

**Comment by robcza** [comment]
I've just rerun the botnet with the changes of yours and it works

**Pull request closed without merging**
