### PR TITLE
Better bot test interface proposal

### PR DESCRIPTION
**Pull request by Phantasus**
Hi there :-)

I have the following proposal for an improved interface for
testing one individual bot (e.g a parser), which I had in my mind
before some business related "inconveniences" hit me right after 
the last unit-test PR (#229). I hope I don't have to deal with 
people who cause such business related nonsense ever again.

Here is how this "improved" interface looks like at the moment:
```
class TestBotTestCase(BotTestCase):
  def setUp(self):
    self.bot_type = TestBot
    self.reset_bot()

  def test_bot_run():
    self.input_queue = ["1.1.2.3\t2.2.4.5\t2015-06-11 16:49:42.262784"]
    expected_event = {"feed": "test", 
                                 "feed_url": "hxx://127.0.0.1",
                                 "type": "brute-force", 
                                  "reported_source_ip": "1.1.2.3",
                                  "reported_destination_ip": "2.2.4.5",
                                  "source_time": "2015-06-11 16:49:42.262784" }
    self.run_bot()
    self.assertLogLengthEqual(20)
    self.assertLoglineEqual(0, "Bot is starting", "INFO")
    self.assertNotRegexpMatchesLog("ERROR")
    self.assertRegexpMatchesLog("WARNING - It is soo awesome, we put also a warning there")
    self.assertEventAlmostEqual(0, expected_event)
```

That code can be found in full in `intelmq/tests/lib/bot.py` if you want that I choose
a different unittest framework -- no problem. Or if you think something needs to be improved,
let me hear it :-)

Here is the list of new assertions which this PR includes for the "better bot testing interface":
1. `assertLoglineEqual`, asserts that the fields of a specific logline which was generated by a bot is equal.
2. `assertRegexpMatchesLog`, asserts that a regular expression matches against the whole log generated by a tested bot.
3. `assertNotRegexpMatchesLog`, asserts that a regular expression matches NOT against the whole log generated by a tested bot. 
4. `assertLogLengthEqual`, asserts that the log has the given lines. 
5. `assertEventAlmostEqual`, asserts that the specified event at a specific position in the output queue of a tested bot is almost equal to a given dict. 

I hope that explanation is helpful to you :-)

### CODE REVIEW

**Comment by aaronkaplan** [comment]
Hi @phantasus,

Cool. I will definitely look at it carefully when I am back from my travels. 

Thanks!!

---
Mobile

**Comment by Phantasus** [comment]
@aaronkaplan very cool :-) Just for information, this PR actually adds only two new things to the unit-test PR (#229). I wasn't sure if I should make a PR to that PR or to master. I chose master because of a little less confusing merging procedure. And I would like to have to this as readable and understandable as possible.

So what does it add new?
1. Add a function for parsing a logline to lib/utils …  (ecf70c0)
2. Add proposal for a BotTestCase … (1282f57)

I think I don't touch it anymore or it would be not reviewable. But when it goes through
I could add TestCases for each parser bot we have in the repo and then we could try
to begin to transition to v1.0-beta. Which could be difficult as I don't have access to 
all data sources here :-/

**Comment by sebix** [comment]
Can be closed. Everything is included in #282.

**Comment by SYNchroACK** [comment]
Thank you @Phantasus 
Thank you @sebix

**Pull request closed without merging**
