### PR TITLE
Names queues #1088

### PR DESCRIPTION
**Pull request by e3rd**
ready for comments

### CODE REVIEW

**Comment by e3rd** [comment]
I've got some problems with pushing this. 

`travis-ci/pr` passes
`travis-ci/push` fails (what's the difference between them by the way?)
Python 3.4 passes, others fail on cymru/test_expert.py . It seems to me there is nothing in common with my changes – or am I wrong?

**Comment by wagner-certat** [comment]
> travis-ci/pr passes
> travis-ci/push fails (what's the difference between them by the way?)

The difference is: push is the head of the branch to be merged and pr is the merged branch (if a merge is possible without conflict).

> It seems to me there is nothing in common with my changes

Most probably, yes.

**Comment by e3rd** [comment]
Yeah, it seems one ASN from a test changed. I corrected it and everything's now successful. You can merge this when you're ready :)

**Comment by wagner-certat** [comment]
I now added the special path `_on_error` as discussed in #1133 @SYNchroACK

**Comment by wagner-certat** [comment]
Thanks @e3rd for your efforts!

**Pull request merged**
