### PR TITLE
Add a github workflow that runs pycodestyle on the repository

### PR DESCRIPTION
**Pull request by schacht-certat**
This also removes the pycodestyle related stuff from travis

### CODE REVIEW

**Review by wagner-certat — CHANGES_REQUESTED** [review]
The codestyle entry in `.travis.yml`'s include section also needs to be removed.

**Comment by schacht-certat** [comment]
> The codestyle entry in `.travis.yml`'s include section also needs to be removed.

done. (I wasn't sure if it was interfering with anything if it was still there...)

**Comment by schacht-certat** [comment]
I have now also added another commit containing a python script that posts the output of `pycodestyle` as review to a PR. If you want that in a separate PR, feel free to tell me, I just thought that would fit together.

**Review by wagner-certat — APPROVED** [review]
Thanks!

**Pull request merged**
