### PR TITLE
ENH: Added Log4shell shadowserver feed

### LINKED ISSUE #2131: Log4j - Collector & Parser
Dear All,

May i ask whether you were thinking to add Log4j for shadowserver feeds within its collector api and parser?

Perhaps we can be of assistance?

Regards
Matthew

### PR DESCRIPTION
**Pull request by waldbauer-certat**
Added the log4shell shadowserver feed :)

Fixes #2131

### CODE REVIEW

**Comment by aaronkaplan** [comment]
@waldbauer-certat did you check if this gets obsoleted by https://github.com/certtools/intelmq/pull/2143 ?

**Comment by elsif2** [comment]
Please note that the Log4shell Special Report is handled by the 'special' report parser.

**Comment by waldbauer-certat** [comment]
> @waldbauer-certat did you check if this gets obsoleted by #2143 ?

Ah missed that :/ But if "special" is capable of log4shell, its obsolete.

**Comment by sebix** [comment]
The file names in the mapping differ.
`scan_log4shell_vulnerable` (this PR) vs `special` (PR #2143)

**Comment by elsif2** [comment]
The log4shell reports were sent with file names like '2021-12-22-special-my_org_name-asn.csv'.

**Comment by sebix** [comment]
Okay, so is the mapping by @waldbauer-certat for some other report then?

**Comment by elsif2** [comment]
No, the Log4shell report is a point in time instance of a 'special' report.  We use the 'special' report type to send out timely notifications for events where we don't already have an established report  type.

**Comment by sebix** [comment]
@waldbauer-certat can you please check if this change is actually needed given the information from @elsif2 about the special report?

**Comment by elsif2** [comment]
This change is not needed.

**Pull request closed without merging**
