### PR TITLE
'enabled' parameter clarification

### PR DESCRIPTION
**Pull request by SYNchroACK**
related to #825 

@sykaeh please check and give your feedback :) Thank you!

### CODE REVIEW

**Comment by SYNchroACK** [comment]
@sebix I tried locally fix the config test but no luck. If you have chance, can you double-check this one? Thank you mate.

**Comment by sykaeh** [comment]
@SYNchroACK I thought we decided **not** to add it `defaults.conf` since it is not like the other parameters and just clarify it in the documentation.

(The config test fails because `defaults.conf` needs to be sorted in alphabetical order)

**Comment by wagner-certat** [comment]
That's not how the parameter works and is intended to work.

> @sebix I tried locally fix the config test but no luck. If you have chance, can you double-check this one? Thank you mate.

It's simply not sorted.

**Comment by SYNchroACK** [comment]
> @SYNchroACK I thought we decided not to add it defaults.conf since it is not like the other parameters and just clarify it in the documentation.

I added it to default.conf because its the only way for IntelMQ-Manager to get it loaded on the interface.
I think with this approach is 99% easy for the user to understand and proceed without need to learn another way to do the things...the user will simply configure the bot with this parameter like other parameter. I just did not find any clear and easy solution from the user point of view. @sykaeh go ahead and suggest another approach (the pull req will not merge without your feedback to my comment) :)

**Comment by wagner-certat** [comment]
On 01/10/2017 08:29 PM, SyNchroAcK wrote:
>
> I added it to default.conf because its the only way for
> IntelMQ-Manager to get it loaded on the interface.
>
You just need to add it in the manager:
*
https://github.com/certtools/intelmq-manager/blob/1a7bfabd93fa781772c1abf09a00f8841babf63c/intelmq-manager/js/main.js#L96
*
https://github.com/certtools/intelmq-manager/blob/1a7bfabd93fa781772c1abf09a00f8841babf63c/intelmq-manager/js/runtime.js#L22
*
https://github.com/certtools/intelmq-manager/blob/1a7bfabd93fa781772c1abf09a00f8841babf63c/intelmq-manager/js/static.js#L32

**Comment by SYNchroACK** [comment]
Closed due a conflit with my branchs on forked repo. Re-opened on #838

**Pull request closed without merging**
