### PR TITLE
New bots, parsers and outputs

### PR DESCRIPTION
**Pull request by helderfernandes1279**

### CODE REVIEW

**Comment by SYNchroACK** [comment]
@helderfernandes1279 , Is it possible for you to make different pull requests for the different features:

```
Pull request 1 (TCP Collector):
intelmq/bots/collectors/tcp/__init__.py
intelmq/bots/collectors/tcp/collector.py

Note: this bot is bot named 'intelmqlistner' that you commit in this pull req
```

```
Pull request 2 (UDP Collector):
intelmq/bots/collectors/udp/__init__.py
intelmq/bots/collectors/udp/collector.py

Note: this bot is bot named 'syslog' that you commit in this pull req
```

```
Pull request 3 (XMPP Collector):
intelmq/bots/collectors/xmpp/__init__.py
intelmq/bots/collectors/xmpp/collector.py
```

```
Pull request 4 (TCP Output):
intelmq/bots/outputs/tcp/__init__.py
intelmq/bots/outputs/tcp/output.py

Note: this bot is bot named 'IntelMQAgent' that you commit in this pull req
```

We rest of the commits we can discuss after we handle all the pull request mentioned before. Its a lot of work for eeryone to test and check your awesome work! ;D

Thank you @helderfernandes1279

**Comment by robcza** [comment]
@helderfernandes1279 will this eventually be fixed for the recent state of IntelMQ? Missing the Shadowserver parsers a lot

**Comment by sebix** [comment]
@robcza You can cherry-pick cc446fc into a branch of your fork, rebase on master, add tests :), and create a PR.

**Comment by robcza** [comment]
@sebix just making sure whether there is anything going on or not :) Direct cherry-picking seems to be a problem as I'm not able to find the source repo/branch. I can do it manually however it does not feel appropriate

**Comment by sebix** [comment]
@robcza We don't have feedback since half a year, so I think it's ok. Already did it the same with some other PRs.

    git remote add helderfernandes1279 git@github.com:helderfernandes1279/intelmq.git
    git remote update
    git checkout -b shadowserver
    git cherry-pick cc446fc

And follow the instructions, they are basically the same as for rebasing.

**Comment by helderfernandes1279** [comment]
I didn't check this latest version yet, but I think that I wil check that as soon as possible.......

**Comment by robcza** [comment]
@sebix can not deal with ```fatal: bad revision 'cc446fc'``` while cherry-picking
I believe, it is a problem with cherry-picking a commit from pull request, which is described in here: https://it-offshore.co.uk/code/47-git-cherry-pick-pull-request-fatal-bad-revision However, proposed solution doe not work for me either :) Any idea?

**Comment by sebix** [comment]
Please show your remotes:

    git remote -v

Btw: `git remote update` fetches all sources from all remote repositories

**Comment by robcza** [comment]
```
git remote -v
helderfernandes1279	https://github.com/helderfernandes1279/intelmq.git (fetch)
helderfernandes1279	https://github.com/helderfernandes1279/intelmq.git (push)
origin	https://github.com/robcza/intelmq.git (fetch)
origin	https://github.com/robcza/intelmq.git (push)
upstream	https://github.com/certtools/intelmq.git (fetch)
upstream	https://github.com/certtools/intelmq.git (push)```

**Comment by sebix** [comment]
I'm working on some shadowserver parsers in my feature branch, I used the existing ones in v0.9 branch as base, using:

    git checkout v0.9 intelmq/bots/parsers/shadowserver

That pulls in the given files into the current branch.

https://github.com/sebix/intelmq/tree/bugfixes

**Comment by sebix** [comment]
- [x] XMPP collector: we have one
 - [x] shadowserver parser: in master too
 - [ ] Syslog collector, we want this, but we can postpone it to 1.1 https://github.com/certtools/intelmq/pull/171/commits/0666a8167d4f980347b01d41550992fab014a472
 - [ ] Intelmq collector: basically a tcp collector, opening a local port, can be postponed to 1.1 https://github.com/certtools/intelmq/pull/171/commits/d64673f96473143a88d5ee0a0279d7677ae782c0
 - [x] intelmq output, basically the tcp output, but sending b64-encoded data, not json
 - [x] phishtank parser fixes: in master too

**Comment by SYNchroACK** [comment]
I talked with @helderfernandes1279 and we decided that is ok to close this pull request. However, I created two new issues ( #848 and #849 ) tagged as 'feature request' for v1.1 milestone.

**Pull request closed without merging**
