### PR TITLE
ZeuS, Palevo and Feodo trackers

### PR DESCRIPTION
**Pull request by robcza**
collectors and parsers for abuse.ch projects

### CODE REVIEW

**Comment by SYNchroACK** [comment]
@robcza , what do you think about collect the information from RSS sources instead of a simple list:

https://zeustracker.abuse.ch/feeds.php

Give me your opinion and lets decide together ;)

**Comment by SYNchroACK** [comment]
Sorry. Due branches changes, this pull req was automatically closed. @robcza can you give me feedback about the collection procedure that I mentioned in the previous comment?

**Comment by robcza** [comment]
The reason is to have additional information (ASN, CC, level, etc.) included or am I missing something?

**Comment by SYNchroACK** [comment]
yes... it has more context information that is useful for analysis

**Comment by robcza** [comment]
makes sense :) i'll rewrite those bots and create a new pull request

**Pull request closed without merging**
