### PR TITLE
Feeds doc + gen_feeds_doc tool

### PR DESCRIPTION
**Pull request by SYNchroACK**

### CODE REVIEW

**Comment by SYNchroACK** [comment]
@wagner-certat I dont understand why travis is failing. :/

**Comment by wagner-certat** [comment]
Opened SYNchroACK/intelmq#6 with more fixes. Please have a look at them. Then I am fine with this PR

**Comment by wagner-certat** [comment]
There are updates to the Feeds: #1170

**Comment by SYNchroACK** [comment]
> There are updates to the Feeds: #1170

done

**Pull request merged**
