### PR TITLE
Add Shadowserver Outdated-DNSSEC-Key(-IPv6)

### PR DESCRIPTION
**Pull request by th-certbund**

### CODE REVIEW

**Comment by th-certbund** [comment]
Shadowserver confirmed request to change 'cc_*' to 'dst_*' in the csv header.

**Comment by wagner-certat** [comment]
Could also be classified as misconfiguration, but outage is also interesting

cc @aaronkaplan

**Comment by th-certbund** [comment]
I also thought of a new type "misconfiguration" because "outage" is more physical... I'll propose to add this to the eCSIRT taxonomy.

**Comment by wagner-certat** [comment]
> I also thought of a new type "misconfiguration" because "outage" is more physical... I'll propose to add this to the eCSIRT taxonomy.

If you are fast it could be discussed today

**Pull request merged**
