### PR TITLE
modify expert: Lowercase all malware names in morefeeds config.

### PR DESCRIPTION
**Pull request by swilde**
The morefeeds config is identical to our current customer setup and
used by our packaging to be the readily available config for the
modify bot.  As per customer request all malware names should be
normalized to lower case.  (Capitalized names would be prefered if it
would be possible to capitalize arbitrary matches in modify bot, but
this is currently not feasible.)

### CODE REVIEW

**Comment by sebix** [comment]
please have a look at this @aaronkaplan

**Comment by dmth** [comment]
Please be aware of https://github.com/certtools/intelmq/pull/745

**Comment by sebix** [comment]
I will fix the merge conflicts ;)

**Comment by aaronkaplan** [comment]
It's totally OK for me to have all malware names lowercase . Same for identifiers.

**Comment by aaronkaplan** [comment]
Can be merged from my PoV

**Pull request merged**
