### PR TITLE
Taxonomy beta fix

### PR DESCRIPTION
**Pull request by Th4nat0s**
Here the quick "run" fix

### CODE REVIEW

**Comment by SYNchroACK** [comment]
@Th4nat0s , again, you change the whole file so i cant see what was your changes.... :S

**Comment by SYNchroACK** [comment]
Got it now, but please, do not change the whole file...

**Comment by Th4nat0s** [comment]
I don't agree, I had change the code (first fix).. then fixed the json... It had TAB in it !! :)... I can't let it like this.. It's not possible poor json... :)

**Comment by SYNchroACK** [comment]
Im just trying to say that do not mix pull req to fix bugs with pull req to re-organize a file like dos2unix etc... well...pull req accepted

**Comment by Th4nat0s** [comment]
Hi, 

Sorry again about that, what do you prefers for code cleanup (when it's really...  crlf.. you see). Do you prefer just a open issue ? Just tell me.. No prob.

**Comment by SYNchroACK** [comment]
Hey @Th4nat0s  :)
No. To cleanup the code I need a pull req separated without any improvements...just cleanup.
Thank you for your help _o_

**Pull request merged**
