### PR TITLE
bug: ctl: handle non-existing bot modules

### PR DESCRIPTION
**Pull request by sebix**
the new function utils.get_bot_module_name returns None if a bot module does not exist, and
importlib.import_module raises an exception when passed None

I added no changelog entry as the faulty code was never released.

previously:
```
Checking for bots.
Traceback (most recent call last):
  File "/usr/bin/intelmqctl", line 33, in <module>
    sys.exit(load_entry_point('intelmq==3.2.2a1', 'console_scripts', 'intelmqctl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/intelmq/bin/intelmqctl.py", line 1295, in main
    return x.run()
           ^^^^^^^
  File "/usr/lib/python3.11/site-packages/intelmq/bin/intelmqctl.py", line 429, in run
    retval, results = args.func(**args_dict)
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/intelmq/bin/intelmqctl.py", line 934, in check
    bot_module = importlib.import_module(utils.get_bot_module_name(bot_config['module']))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 117, in import_module
    if name.startswith('.'):
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'startswith'
```

now:
```
Checking for bots.
Incomplete installation: Bot 'malc0de-parser' not importable.
```

### CODE REVIEW

**Comment by sebix** [comment]
The one check that fails, fails consistently, but for no apparent reason. I already re-ran it with the same result. I has nothing to do with the changed code and it makes no sense that this test only fails on one platform too:
```
=================================== FAILURES ===================================
__________________________ TestAmqp.test_acknowledge ___________________________

self = <intelmq.tests.lib.test_pipeline.TestAmqp testMethod=test_acknowledge>

    @unittest.skipIf(os.getenv('CI') == 'true' and sys.version_info[:2] == (3, 8),
                     'Fails on CI with Python 3.8')
    def test_acknowledge(self):
        self.pipe.send(SAMPLES['normal'][0])
        self.pipe.receive()
        self.pipe.acknowledge()
>       self.assertEqual(self.pipe.count_queued_messages('test')['test'], 0)
E       AssertionError: 1 != 0

intelmq/tests/lib/test_pipeline.py:275: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  pika.channel:channel.py:238 basic_cancel - consumer not found: ctag1.3ba5f52b9bf64f68b7debd8cd4b8e790
```

**Review by kamil-certat — APPROVED** [review]
Good catch

**Comment by kamil-certat** [comment]
re: CI fail - please mark it as skipped and create an issue to investigate it

**Comment by aaronkaplan** [comment]
Thank you @sebix !

**Pull request merged**
