### PR TITLE
Shadowserver updates

### PR DESCRIPTION
**Pull request by monoidic**
This PR:
* adds support for the IPv6 variants of the telnet and Poodle feeds from Shadowserver
* makes the `tag` attribute of some feeds to the `extra.tag` field of the corresponding event if it can contain non-constant data, e.g `plex` for the SSDP feed rather than `ssdp`, or a supplementary `iot` tag for the FTP and telnet feeds or `vpn` for FREAK
* adds tests for the v6 variants of the feeds + fixes `test_broken`, which was broken by the addition of the new optional `extra.tag` field

### CODE REVIEW

**Comment by sebix** [comment]
Looks good semantically. If someone can verify the correctness and ~donates a changelog line~ (fixed), this is ready for merge.

> makes the `tag` attribute of some feeds to the `extra.tag` field of the corresponding event if it can contain non-constant data, e.g `plex` for the SSDP feed rather than `ssdp`, or a supplementary `iot` tag for the FTP and telnet feeds or `vpn` for FREAK

IIRC all fields which were not mapped explicitly, are saved in extra implicitly. So this changes "just" makes it explicit.
https://github.com/certtools/intelmq/blob/7ebb8e16d821c372a44b077dd18a151c07f75807/intelmq/bots/parsers/shadowserver/parser.py#L202-L209

**Comment by sebix** [comment]
@elsif2 for review

**Comment by elsif2** [comment]
The above changes are superseded by #2143.

**Comment by sebix** [comment]
@elsif2 Reminder on this PR as well.

**Comment by elsif2** [comment]
Thank you for your contribution.  This PR has been obsoleted by recent updates. All Shadowserver reports are now supported in the current develop branch and will be included in the 3.1.0 release.

**Pull request closed without merging**
