### PR TITLE
add re.IGNORECASE (iregex) support to the harmonisation.conf

### PR DESCRIPTION
**Pull request by aaronkaplan**
add the ignore case thing for regexps for the harmonisation

### CODE REVIEW

**Comment by aaronkaplan** [comment]
comments?

**Comment by sebix** [comment]
I'd like to discuss this and #587 first, please don't merge yet.

**Comment by aaronkaplan** [comment]
ok

**Comment by aaronkaplan** [comment]
discussed this with @sebix : for the case of transport protocol definitons ("udp" vs. "UDP")  we agreed to normalise by lowercasing everything. However, I believe keeping the "iregex" possibility in lib/message.py in a742c034c80249e80d2f280fd0dc8a72236e8a57 is actually handy right now. We can remove it, should it not be needed anywhere else.

**Pull request merged**
