### PR TITLE
Modify bot: Prepare for more example configs

### PR DESCRIPTION
**Pull request by gsiv**
In order to be able to add more configurations without filling up the bot's root directory I would like to move the configs to an `example` subdirectory.  We already have an additional modify.conf that we would like to add.

### CODE REVIEW

**Comment by aaronkaplan** [comment]
looks good for me. @sebix ?

**Comment by aaronkaplan** [comment]
The build is failing here...why?

**Comment by sebix** [comment]
The configuration couldn't be loaded :D

**Comment by aaronkaplan** [comment]
Yeah I saw that in the nose test output. But why?

---
Mobile

**Comment by sebix** [comment]
Because the filename in [intelmq/tests/bots/experts/modify/test_expert.py#L55](https://github.com/certtools/intelmq/blob/master/intelmq/tests/bots/experts/modify/test_expert.py#L55) needs to be adapted accordingly.

**Comment by aaronkaplan** [comment]
ok, travis-CI gave green lights. Thx!

**Pull request merged**
