### PR TITLE
New Bot for Shadowserver feeds

### PR DESCRIPTION
**Pull request by dmth**
This PR introduces a new strategy to parse Shadowserver feeds.

**Known ToDos:**
 * Add Conversion Functions for some Data, as @sebix already suggested
  * IPMI: `*_auth`, `usernames`, `nulluser` and `anon_login` replace  yes/no with true/false
  * IPMI: `default_kg` replace the - or default  with None
  * Hostnames can contain IP's which has to be handled.
 * Add this Bot to the documentation or update the documentation.

### CODE REVIEW

**Comment by sebix** [comment]
Your PR also includes many other changes, Filecollector, XMPP, cymru_infected, json-parser etc. I guess this is not intended?

**Comment by dmth** [comment]
> Your PR also includes many other changes, Filecollector, XMPP, cymru_infected, json-parser etc. I guess this is not intended?

uuuh, thank your for noting this. It was not intended. Seems I've forked this branch from the wrong working copy. Let's see if we can fix that easily.... I fear this will require a lot of cherry picking.

**Comment by aaronkaplan** [comment]
On Sun, Jun 26, 2016 at 11:59:04PM -0700, Dustin Demuth wrote:
> > Your PR also includes many other changes, Filecollector, XMPP, cymru_infected, json-parser etc. I guess this is not intended?
> 
> uuuh, thank your for noting this. It was not intended. Seems I've forked this branch from the wrong working copy. Let's see if we can fix that easily.... I fear this will require a lot of cherry picking.
> 

Hey Dustin,

I'll be happy to include the code into the main branch as soon as this
gets sorted out.
Would it help if I test with this contribution in the mean time while it
gets cherry-picked. 
Sorry to hear that this creates extra work, but I tend to agree with
Sebix here... it would be much cleaner to have the PRs separated.

Best,
a.

---
Never,
never,
never
give
up!
(winston churchill)

**Comment by dmth** [comment]
Thank you for your offer, feel free to test the shadowserver parser.

**Comment by sebix** [comment]
Current behavior for extra:

    'extra': '{"sic": 654321, "response_size": 116, "naics": 123456}',
new one:

    'extra': '{"shadowserver": {"naics": "123456", "sic": "654321", "size": ' '"116", "tag": "chargen"}}',

If we switch to this new behavior, we also should change the documentation about this field.

**Pull request closed without merging**
