### PR TITLE
HTML Table Parser Bot

### PR DESCRIPTION
**Pull request by kbrajneesh**
This parser is a configurable bot just like Generic CSV parser and can replace most of the parser which parse from HTML Table.

### CODE REVIEW

**Comment by kbrajneesh** [comment]
I have tried to fix all the suggestions. Please see [pulls#1381](https://github.com/certtools/intelmq/pull/1381/commits/aca1de1ad458b45e54905fb978907bdb4d0c0bcb) for a few additions.
`html_table_multivalue_cols.data` is from Precisionsec Agent Tesla IOC Feed, which is not yet listed here.
`html_table_with_attribute.data` is made up data of different feeds.

**Comment by wagner-certat** [comment]
> I have tried to fix all the suggestions. Please see [commit#aca1de1](https://github.com/certtools/intelmq/pull/1381/commits/aca1de1ad458b45e54905fb978907bdb4d0c0bcb) for a few additions.

Thanks, looks very good!

> `html_table_multivalue_cols.data` is from Precisionsec Agent Tesla IOC Feed, which is not yet listed here.

Thanks, I guess it is https://precisionsec.com/threat-intelligence-feeds/agent-tesla/

**Comment by wagner-certat** [comment]
Related following commits: bf9a0c84904a9e4d17157927299c7e0ac58413b2 5db411380c5377d82891d0841e8780d1a6118689

**Comment by kbrajneesh** [comment]
Thanks.

Also we can create an expert bot based on same concept to enhance feeds such as `Feodo Tracker Browse` with url https://feodotracker.abuse.ch/browse/host/<source.ip> and `Ransomware Tracker` with url https://ransomwaretracker.abuse.ch/host/<source.ip|source.fqdn>.

Have a glimpse https://github.com/navtej/intelmq/pull/97/files

**Comment by wagner-certat** [comment]
> Thanks.
> 
> Also we can create an expert bot based on same concept to enhance feeds such as `Feodo Tracker Browse` with url https://feodotracker.abuse.ch/browse/host/<source.ip> and `Ransomware Tracker` with url https://ransomwaretracker.abuse.ch/host/<source.ip|source.fqdn>.
> 
> Have a look at https://github.com/navtej/intelmq/pull/97/files

Wow! Really cool work! I'm impressed :)

**Comment by navtej** [comment]
https://github.com/navtej/intelmq/tree/latest has some bots which we were unable to send upstream. Let's see if we selectively merge some more.

**Pull request merged**
