### PR TITLE
Expert filter

### PR DESCRIPTION
**Pull request by e3rd**
jen kostra budouciho filter bota v /bots/ + deskripce v BOTS

### CODE REVIEW

**Comment by SYNchroACK** [comment]
Dear @e3rd 
Why did you close the pull request? Can I help you? I would like to discuss with you about the content of pull request. :)

Thank you

**Comment by e3rd** [comment]
Hello Tomás,

this pull was requested by mistake. It should have been included in our
private fork only, not to the main project. It is not working yet. I ll
recreate another pull request when we are done :)
Keen regards,
 Edvard

**Comment by aaronkaplan** [comment]
On Apr 29, 2015, at 2:03 PM, e3rd <notifications@github.com> wrote:

> Hello Tomás,
> 
> this pull was requested by mistake. It should have been included in our
> private fork only, not to the main project. It is not working yet. I ll
> recreate another pull request when we are done :)
> Keen regards,
> Edvard
> 

Cool, thanks Edvard!
a.

**Comment by SYNchroACK** [comment]
We will wait for a new pull req with that new functionality :)

Please check the current one:
https://github.com/certtools/intelmq/tree/v1.0-final/intelmq/bots/experts/filter

Thank you @e3rd

**Pull request closed without merging**
