### PR TITLE
Update _config.py

### PR DESCRIPTION
**Pull request by oencarnacion**
location corrections and confirmation of some reports that shadowserver still sends to its recipients

### CODE REVIEW

**Comment by oencarnacion** [comment]
Update

**Comment by sebix** [comment]
ping @elsif2 for review

**Comment by elsif2** [comment]
> ping @elsif2 for review

Once #2143 is accepted, any user submitted changes between the `CONFGEN` markers will be overwritten since the intelmq/bots/parsers/shadowserver/_config.py is machine generated from our report schema.

The following are all duplicates except scan_epmd which was added to the pull request today.

| #2199 | #2143 |
| --- | --- | 
| open6_telnet | scan6_telnet |
| open_amqp | scan_ampq |
| open_scan_ddos_middlebox | scan_ddos_middlebox |
| open_scan_dvr_dhcpdiscover  | scan_dvr_dhcpdiscover |
| scan_epmd | scan_epmd |
| ssl_poodle46_vulnerable_servers (165 & 597) | scan_ssl_poodle |
| scan_ics | scan_ics |
| scan_kubernetes | scan_kubernetes |
| scan_quic | scan_quic |
| scan_socks | scan_socks |
| scan_ssh | scan_ssh |
| accessible_ssl | scan_ssl |
| device_id | device_id |
| open_mysql | scan_mysql |
| open6_ssl | scan6_ssl |
| open6_ssh | scan6_ssh |
| open_smtp | scan_smtp |
| open6_smtp | scan6_smtp |

**Comment by oencarnacion** [comment]
Nice!  Will the request be accepted by you?

Enviado desde mi Samsung Mobile de Claro
Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sebix** [comment]
Dear @elsif2,

As you are the maintainer of the shadowserver-components in IntelMQ, I kindly ask you to review and decide on the Pull Requests, including this one?

Thanks

**Comment by elsif2** [comment]
All supported report types have been updated in the current develop branch and will be included in release 3.1.0.

**Comment by sebix** [comment]
@elsif2 Thank you for conclusion.

@oencarnacion Nevertheless this PR has been obsoleted by the recent activities, I esteem your willingness to contribute and respect the time you've invested in it.

**Pull request closed without merging**
