### PR TITLE
Address issue #584

### PR DESCRIPTION
**Pull request by aaronkaplan**
@sebix pls review

### CODE REVIEW

**Comment by sebix** [comment]
I have a few questions here:
* IANA lists some deprecated protocols (argus, swipe, micp, sm), do we want them?
* IANA list and /etc/protocols and this list differs, e.g:
  The diff for iana's list with my /etc/protocols:
```
> diff -i etcproto ianaproto 
49c49
< mhrp
---
> DSR
82a83
> IPTM
88d88
< sprite-rpc
120c120
< isis
---
> ISIS over IPv4
123c123
< crudp
---
> UDP
127a128
> IP
131c132
< mobility
---
> Mobility Header
133a135,139
> manet
> HIP
> Shim6
> WESP
> ROHC
```

Some names also differ (mobility vs. mobility header, isis vs. isis over IPv4).

How to handle all these differences?

**Comment by aaronkaplan** [comment]
> On 21 Jul 2016, at 16:35, Sebastian <notifications@github.com> wrote:
> 
> I have a few questions here:
> 
> 	• IANA lists some deprecated protocols (argus, swipe, micp, sm), do we want them?
> 	• IANA list and /etc/protocols and this list differs, e.g: The diff for iana's list with my /etc/protocols:
> > diff -i etcproto ianaproto
> 49c49
> < mhrp
> ---
> > DSR
> 82a83
> > IPTM
> 88d88
> < sprite-rpc
> 120c120
> < isis
> ---
> > ISIS over IPv4
> 123c123
> < crudp
> ---
> > UDP

^^^^^ important ! Case sensitivity or not!

> 127a128
> > IP
^^^^^ important ! Case sensitivity or not!

> 131c132
> < mobility
> ---
> > Mobility Header
> 133a135,139
> > manet
> > HIP
> > Shim6
> > WESP
> > ROHC
> 

The rest is completely irrelevant in practical environment


> Some names also differ (mobility vs. mobility header, isis vs. isis over IPv4).
> 
ignore. Take it out of the list if you want to.

**Comment by aaronkaplan** [comment]
We don't have any re.IGNORECASE in any of the regex matchings ... hm...

**Comment by sebix** [comment]
> ^^^^^ important ! Case insensitivity needed

I ignored casesensitivity in the diff posted above (flag -i).

> We don't have any re.IGNORECASE in any of the regex matchings ... hm...

Different cases are be problematic, as we usually compare events with ==. We should lower everything.

But we could defie a new type like "LowercaseString". Its sanitize-method automatically lowers all characters. This is also useful for many other fields.

**Comment by aaronkaplan** [comment]
merging but we know that we still need to address the case senstivitiy issue.

**Pull request merged**
