### PR TITLE
Feature, Header in URL fetcher bot.

### PR DESCRIPTION
**Pull request by Th4nat0s**
Sometimes you got authentication key required in headers (http Authorization for basic, or key for misp by example) not only a key in the url.

This quick fix allow the definition of header per feed. The field is not mandatory to be defined.

Usage:
 ```
 "phishtank-collector": {
    "error_procedure": "retry",
    "error_retry_delay": 30,
    "error_log_message": true,
    "error_dump_message": true,
    "url": "http://data.phishtank.com/data/online-valid.csv",
    "header": "x-test: helloworld",
    "rate_limit": 3600
  },

```
And it's added to http request.

```
0030  39 08 82 c3 00 00 47 45 54 20 2f 64 61 74 61 2f   9.....GET /data/
0040  6f 6e 6c 69 6e 65 2d 76 61 6c 69 64 2e 63 73 76   online-valid.csv
0050  20 48 54 54 50 2f 31 2e 31 0d 0a 41 63 63 65 70    HTTP/1.1..Accep
0060  74 2d 45 6e 63 6f 64 69 6e 67 3a 20 69 64 65 6e   t-Encoding: iden
0070  74 69 74 79 0d 0a 48 6f 73 74 3a 20 64 61 74 61   tity..Host: data
0080  2e 70 68 69 73 68 74 61 6e 6b 2e 63 6f 6d 0d 0a   .phishtank.com..
0090  43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73   Connection: clos
00a0  65 0d 0a 58 2d 54 65 73 74 3a 20 68 65 6c 6c 6f   e..X-Test: hello
00b0  77 6f 72 64 72 64 0d 0a 0d 0a                     wordrd....

```

### CODE REVIEW

**Comment by SYNchroACK** [comment]
@Th4nat0s thank you!

Some adjustmensts:
* remove README changes
* why in your pull requests you overwrite all lines with the new ones... may be is your editor... can you check that?

**Comment by Th4nat0s** [comment]
No...  It's me... i dislike CRLF I had dos2unixed them... Is it an issue ?

I will remove README got some pain with beta branch merged after my initial github fork... I always got issues with branch ! :)

**Comment by Th4nat0s** [comment]
hi, 
Readme is fixed.

**Comment by aaronkaplan** [comment]
---
Mobile


> On 06.06.2015, at 20:45, Thanat0s <notifications@github.com> wrote:
> 
> No... It's me... i dislike CRLF I had dos2unixed them... Is it an issue ?
> 

No :) thanks a lot. This also disturbed me

**Comment by SYNchroACK** [comment]
I agreed with you regarding CRLF. In this case, I would like to suggest to make a separated pull req with all beta-branch files reviewed. Then its much more easy for me to check your changes for each contribution.

Is it ok for you do it? Thank you.

**Comment by SYNchroACK** [comment]
Forget it. Conversion done: d49d9fcacf1f1d5f0dd5cc915f9e0a9ba0314536

Update your pull req and then i can check the lines that you changed. Thank you

**Comment by Th4nat0s** [comment]
will try to "remerge" tomorrow...

**Comment by Th4nat0s** [comment]
Is theyre any issue here ?

**Comment by sebix** [comment]
You can combine the commits by using `git rebase -i origin/v1.0-beta`. As dos2unix has been applied to the repo already, the changes should then be smaller and only include the changed lines.

**Comment by sebix** [comment]
This PR needs to be corrected since it includes 998 commits and the target branch does not exist anymore, but it is not resolved as we want this addition, I think?

@Th4nat0s: Please don't pull (fetch and merge) from remote, use rebase instead.

**Comment by SYNchroACK** [comment]
Sorry. Due branches changes, this pull req was automatically closed. @Th4nat0s please follow the @sebix suggestion. ;)

**Comment by sebix** [comment]
@Th4nat0s: Please see https://github.com/certtools/intelmq/issues/64#issuecomment-130311349 and the following comment. Hope I can help you.

For Merging/Rebasing have a look here: https://www.atlassian.com/git/tutorials/merging-vs-rebasing

**Comment by sebix** [comment]
This feature has been commited here https://github.com/certtools/intelmq/commit/eeb71e1d2e014dae1d64bb1abf68314a3c3d4f6f
Merged in https://github.com/certtools/intelmq/pull/309

**Pull request closed without merging**
