### PR TITLE
Remove startup.conf

### PR DESCRIPTION
**Pull request by sebix**
next step of certtools/intelmq#267

It's still supported, but will be dropped after the feature freeze.

### CODE REVIEW

**Comment by dmth** [comment]
The file should also be removed from "examples"

**Comment by sebix** [comment]
See certtools/intelmq-manager#85 for the changes in the manager.

**Comment by dmth** [comment]
hi, @sebix what's the state of this PR? From my understanding it's still needed.

**Comment by sebix** [comment]
I will merge it this week tough there are not reviews.

**Comment by sebix** [comment]
Merged.

**Pull request closed without merging**
