### PR TITLE
add redis_cache_host to defaults.conf

### PR DESCRIPTION
**Pull request by dominik335**
As it's assumed it's 127.0.0.1

### CODE REVIEW

**Comment by wagner-certat** [comment]
For what is this necessary in particular (it's in the templates for all bots needing a cache) and why not also adding the password and the port? (DB and TTL are specific to the exact usage)

**Comment by dominik335** [comment]
My case was that I had redis running in another container than intelmq so host was different. Not really necessary but helpful. And pass and port would fit too.

**Comment by wagner-certat** [comment]
> My case was that I had redis running in another container than intelmq so host was different. Not really necessary but helpful. And pass and port would fit too.

All bots which need the redis cache should have this parameter it's template/documentation. Where is it missing?

**Comment by dominik335** [comment]
Not aware of any place but for me it was much easier to put it in defaults so I thought it could be good to have that along other redis settings in default.conf. Just that ;)

**Comment by wagner-certat** [comment]
Ok. However, I wouldn't consider this worthwhile (at least in it's current state). Nevertheless, thanks for your willingness to contribute :)

(btw it's invalid JSON syntax, the previous line needs a trailing comma)

**Pull request closed without merging**
