### PR TITLE
Modified sanitation exception handling

### PR DESCRIPTION
**Pull request by robcza**
Proposed this change based on this issue: https://github.com/certtools/intelmq/issues/374
Actually running this branch for quite a while and seems stable. I can see one possible flaw, that just the last exception is recorded this way.

Should I have list of exceptions there and add them as they appear? That would mean to log all of them in the end.

### CODE REVIEW

**Comment by robcza** [comment]
Ok, I get it, it breaks the tests actually, as it is not raising the exception right away. What do you think? Is this the right way to go and tests have to be changed or is this a wrong direction?

**Comment by sebix** [comment]
I'm not sure if this actually solves the issue. I would have just put a try-except in the parsers' loops and called a modified dump routine for single lines that are malformed/problematic. You just saved the error message some where. It will be overridden and forgotten. The malformed data will never be reported, data will be silently thrown away.

**Comment by mauroasilva** [comment]
I have to agree with @sebix ... I think the best approach would be to have something similar to the already implemented message dump that dumps problematic lines. That would actually also help with the #406 issue.

**Comment by robcza** [comment]
@sebix try-except in the parsers is another complexity for the coder, that is why I tried to move that on the lib level. Malformed data are logged in my code, not actually forgotten, however not really prepared to reprocess.

Could we dump the message without changing anything on the parser level?

**Pull request closed without merging**
