### PR TITLE
Shadowserver 20220909

### PR DESCRIPTION
**Pull request by elsif2**
Many thanks to Eric Halil for testing the 3.1 pre-release changes.

The following field types have been standardized across all Shadowserver reports:

  - destination.fqdn (validate_fqdn)
  - destination.url (convert_http_host_and_url)
  - extra.browser_trusted (convert_bool)
  - extra.duration (convert_int)
  - extra.end_time (convert_date_utc)
  - extra.freak_vulnerable (convert_bool)
  - extra.ok (convert_bool)
  - extra.password (validate_to_none)
  - extra.ssl_poodle (convert_bool)
  - extra.status (convert_int)
  - extra.uptime (convert_int)
  - extra.version (convert_to_none)
  - source.network (validate_network)

The following report field names have changed to better represent their values:
  - scan_rsync:extra.password renamed to extra.has_password
  - scan_elasticsearch:status renamed to http_code

 Fixed spurious warning on fields that are defined yet empty.

Restored the 'classification.identifier' for `Accessible-HTTP` to match the previous release.

### CODE REVIEW

**Comment by sebix** [comment]
To fix the codespell action fail, rebase on master and fix these:
```
./NEWS.md:45: unneccessary ==> unnecessary
./NEWS.md:45: identifer ==> identifier
```
and for the codestyle fail, fix these:
```
intelmq/bots/parsers/shadowserver/parser.py:112:20: E713 test for membership should be 'not in'
intelmq/bots/parsers/shadowserver/parser.py:142:20: E713 test for membership should be 'not in'
```

**Comment by elsif2** [comment]
Fixed.

**Comment by sebix** [comment]
I don't know how you rebase that you always end up with duplicated commits. Please use `git rebase develop`. I did that now, which removed 20 spurious commits from the branch.

**Comment by elsif2** [comment]
I did a `git pull --rebase origin develop`

**Pull request merged**
