### PR TITLE
set sandbox_url to malware-distribution

### PR DESCRIPTION
**Pull request by n-marques**
Change Sandbox URL classification type from malware to malware-distribution

### CODE REVIEW

**Comment by wagner-certat** [comment]
related to #1409

**Comment by wagner-certat** [comment]
Hi,

First of all: I agree with the change itself.

This change is also part of a larger commit getting rid of the `malware` type completely: c9e89e762c4111372315c81e98926d323cf74b9d That commit is part of the develop-3.0 branch which will result in the next major release (not a previous patch/maintenance or minor release).

We can prepone this change if we agree this fits into a patch or minor release. I am very hesitant to do this in a patch release as it can cause trouble in any downstream application and dataprocessing. _Maybe_ in minor release? (that would be the develop branch - but it needs some changes/adaptions)

@th-certbund what do you think on that?

**Comment by th-certbund** [comment]
I would prefer to make this change as part of the larger commit for the next major release (3.0).

**Comment by wagner-certat** [comment]
@n-marques Thanks for your input and motivation to contribute and sorry for the begin able to merge your contribution :/

In the meantime I can propose you to use e.g. the modify expert or sieve expert to fix the value in your setup. Example for the modify bot configuration:

```json
[
    {
        "rulename": "Sandbox URL classification.type fix",
        "if": {
            "classification.identifier": "sandbox-url",
            "classification.type": "malware"
        },
        "then": {
            "classification.type": "malware-distribution"
        }
    }
]
```
(untested)

**Pull request closed without merging**
