### PR TITLE
Added new shadowserver files to _config.py

### PR DESCRIPTION
**Pull request by mateodurante**
Added new shadowserver event types and files to _config.py:
- Accessible SOCKS4/5 Proxy
- Open DVR DHCPDiscover

### CODE REVIEW

**Comment by sebix** [comment]
@elsif2 for review

**Comment by elsif2** [comment]
The above changes are superseded by https://github.com/certtools/intelmq/pull/2143.

**Comment by elsif2** [comment]
These changes are superseded by #2143.  This request can be closed.

**Comment by sebix** [comment]
@elsif2 Reminder on this PR as well.

**Comment by elsif2** [comment]
Thank you for your contribution.  This PR has been obsoleted by recent updates. All Shadowserver reports are now supported in the current develop branch and will be included in the 3.1.0 release.

**Pull request closed without merging**
