### PR TITLE
tst: skip tests which require an intelmq installation by default

### LINKED ISSUE #2369: intelmqctl and intelmqdump tests require an installed IntelMQ instance
This is a revival of #2300 (ctl tests require an installed IntelMQ instance). These tests are affected now:

- TestIntelMQController::test_check_handles_syntaxerror_when_importing_bots
- TestIntelMQController::test_check_pass_with_default_runtime
- TestIntelMQController::test_check_passed_with_default_harmonization_and_empty_runtime
- TestIntelMQDump::test_get_dump_for_one_bot
- TestIntelMQDump::test_list_and_select_dump_from_custom_location
- TestIntelMQDump::test_list_and_select_dump_from_global_location
- TestIntelMQDump::test_list_dumps_for_all_bots_from_custom_locations
- TestIntelMQDump::test_list_dumps_for_all_bots_from_default_log_path
- TestIntelMQDump::test_selecting_dump_warns_when_filename_is_ambiguous

the ctl tests have a traceback like this:
```
[  152s]   File "/usr/src/packages/BUILD/.pybuild/cpython3_3.9_intelmq/build/intelmq/lib/utils.py", line 224, in load_configuration
[  152s]     raise ValueError('File not found: %r.' % configuration_filepath)
[  152s] ValueError: File not found: '/etc/intelmq/runtime.yaml'.
[  152s] ERROR    intelmqctl:intelmqctl.py:127 No valid IntelMQ installation found: DistributionNotFound
```
and the dump tests don't find any dumps.

So I suggest to add a new skip-decorator and environment variable to skip tests depending on an installation by default. This also addresses https://lists.cert.at/pipermail/intelmq-dev/2023-May/000610.html

### PR DESCRIPTION
**Pull request by wagner-intevation**
fixes certtools/intelmq#2369

### CODE REVIEW

**Review by kamil-certat — APPROVED** [review]
Approved, but I'd like to see it as an exceptional solution – and in the long term, rather develop solution to fully isolate IntelMQ tests.

**Comment by sebix** [comment]
> Approved, but I'd like to see it as an exceptional solution – and in the long term, rather develop solution to fully isolate IntelMQ tests.

I agree, but I want to add two more points here:
1. as long as the tests require an installation, this solution is acceptable as it ensures isolation. The skips should be removed once the testes are isolated (using mocking).
2. Unit tests that depend on an installation (and are not isolated/mocked) are more accurate and have better coverage, as the mocking can be inaccurate for several reasons. But there are better ways than having such integration tests as part of a test suite which is expected to be isolated.

**Comment by kamil-certat** [comment]
> Unit tests that depend on an installation (and are not isolated/mocked) are more accurate and have better coverage, as the mocking can be inaccurate for several reasons. But there are better ways than having such integration tests as part of a test suite which is expected to be isolated.

just a nit: I believe that if it's possible, it's better to isolate by providing e.g. temporary working directory for tests than mocking, so the full code path is run. I didn't mean `isolation` = `mocking` ;)

**Comment by sebix** [comment]
> > Unit tests that depend on an installation (and are not isolated/mocked) are more accurate and have better coverage, as the mocking can be inaccurate for several reasons. But there are better ways than having such integration tests as part of a test suite which is expected to be isolated.
> 
> just a nit: I believe that if it's possible, it's better to isolate by providing e.g. temporary working directory for tests than mocking, so the full code path is run. I didn't mean `isolation` = `mocking` ;)

Yep, even better!

**Pull request merged**
