### PR TITLE
'enabled' parameter clarification

### PR DESCRIPTION
**Pull request by SYNchroACK**
related to #825

### CODE REVIEW

**Comment by wagner-certat** [comment]
As already said in #825: This is not what you want.

You just need to add it in the manager:
* https://github.com/certtools/intelmq-manager/blob/1a7bfabd93fa781772c1abf09a00f8841babf63c/intelmq-manager/js/main.js#L96
* https://github.com/certtools/intelmq-manager/blob/1a7bfabd93fa781772c1abf09a00f8841babf63c/intelmq-manager/js/runtime.js#L22
* https://github.com/certtools/intelmq-manager/blob/1a7bfabd93fa781772c1abf09a00f8841babf63c/intelmq-manager/js/static.js#L32

**Comment by SYNchroACK** [comment]
> As already said in #825: This is not what you want.
> 
> You just need to add it in the manager:
> 
> https://github.com/certtools/intelmq-manager/blob/1a7bfabd93fa781772c1abf09a00f8841babf63c/intelmq-manager/js/main.js#L96
> https://github.com/certtools/intelmq-manager/blob/1a7bfabd93fa781772c1abf09a00f8841babf63c/intelmq-manager/js/runtime.js#L22
> https://github.com/certtools/intelmq-manager/blob/1a7bfabd93fa781772c1abf09a00f8841babf63c/intelmq-manager/js/static.js#L32

The code that you point on manager solve the technical problem, yes, but does not solve the concept/model issue and is precisely what we are discussing here.

**Comment by wagner-certat** [comment]
Which issue from #825 does this PR address?

**Comment by sykaeh** [comment]
In #825 I only asked to clarify and update the documentation. I have done that in #840. The necessary changes to the intelmq-manager are still outstanding.

**Pull request closed without merging**
