### PR TITLE
Elastic update for 7+

### PR DESCRIPTION
**Pull request by stone-z**
Towards https://github.com/certtools/intelmq/issues/1479

- removes mapping types in Elasticsearch output bot, tests, and elasticmapper
- removes test for raising on template not existing (https://github.com/certtools/intelmq/issues/1480)
- updates Travis Elasticsearch version to 7.6.1

### CODE REVIEW

**Comment by stone-z** [comment]
The failing test is a codestyle test related complaining about a long line in the cymru expert - this line is a url in a comment.

**Comment by wagner-certat** [comment]
> The failing test is a codestyle test related complaining about a long line in the cymru expert - this line is a url in a comment.

I will look into it

**Comment by wagner-certat** [comment]
> The failing test is a codestyle test related complaining about a long line in the cymru expert - this line is a url in a comment.

On travis I only see a fail in the ripe expert tests which is working on the develop branch (just merge it in). Please give more information on the error you are seeing.

**Comment by stone-z** [comment]
Are you able to see [my build output](https://travis-ci.org/github/stone-z/intelmq)?

For me the failing test is:
```
$ if [[ $mode == codestyle ]]; then pycodestyle intelmq/{bots,lib,bin}; fi

intelmq/bots/experts/cymru_whois/lib.py:167:133: E501 line too long (178 > 132 characters)
```

**Comment by stone-z** [comment]
Ok I've updated the branch and now see the ripe expert error and it seems to have restored a test I removed. Will revisit this this weekend.

**Comment by stone-z** [comment]
I see the ripe error also on `develop` so I think it is not related to this PR

https://travis-ci.org/github/certtools/intelmq/jobs/669767267

**Comment by wagner-certat** [comment]
Thank you very much for your efforts and your contribution. Sorry for letting you wait so long, unfortunately I was busy with other stuff these weeks. I hope I can form a new release soon.

I made some additional documentation/maintenance changes in 9385ec57

**Pull request merged**
