### PR TITLE
added Testing.md document. This is a **proposal**

### PR DESCRIPTION
**Pull request by aaronkaplan**
Please review and if you like the strategy , include it in the beta branch. thanks!

### CODE REVIEW

**Comment by sebix** [comment]
Any objections to this proposal?

**Comment by SYNchroACK** [comment]
A little confusing... I dont like it... but if multiple people thing is ok, well... i will agree.. lol

**Comment by sebix** [comment]
I would appreciate some real (implemented) tests for existing bots to understand how the instructions should be implemented.

**Comment by aaronkaplan** [comment]
@SYNchroACK : what's confusing about it? Could you be please a little bit more specific and help us improve it? 
Yes, I agree, we should also have some real tests defined (in a tests/ subdirectory or with a similar mechanism). This document currently only gives a high-level overview.

**Comment by SYNchroACK** [comment]
Sorry. Due branches changes, this pull req was automatically closed. @aaronkaplan "don't pull (fetch and merge) from remote, use rebase instead."

**Pull request closed without merging**
