### PR TITLE
Conversion of Python2 source to Python3 

### PR DESCRIPTION
**Pull request by Phantasus**
Hi,

I tried to make a conversion of the existing python2 source to python3. What do you think?

It converts lib and bots with 2to3 and with manual changing those parts which caused
an error. One of those errors were an unicode conversion error from moving
an event to redis(into queue) and back(from redis queue to event), 
so I would advise you if you test this thing on a setup
where you don't have problems when redis contains errorneous data (and be able to rollback them).

How did I test it?

```
sudo python setup.py install
[intelmq@nox ~]$ ./bin/intelmqctl --botnet start
Starting Botnet...
Starting arbor-collector...
arbor-collector is already running.
Starting arbor-parser...
arbor-parser is already running.
Starting cymru-expert...
cymru-expert is already running.
Starting deduplicator-expert...
deduplicator-expert is already running.
Starting dragon-research-group-ssh-collector...
dragon-research-group-ssh-collector is already running.
Starting dragon-research-group-ssh-parser...
dragon-research-group-ssh-parser is already running.
Starting dragon-research-group-vnc-collector...
dragon-research-group-vnc-collector is already running.
Starting dragon-research-group-vnc-parser...
dragon-research-group-vnc-parser is already running.
Starting file-output...
file-output is already running.
Starting malware-domain-list-collector...
malware-domain-list-collector is already running.
Starting malware-domain-list-parser...
malware-domain-list-parser is already running.
Starting openbl-collector...
openbl-collector is already running.
Starting openbl-parser...
openbl-parser is already running.
Starting sanitizer-expert...
sanitizer-expert is already running.
Starting taxonomy-expert...
taxonomy-expert is already running.
Starting vxvault-collector...
vxvault-collector is already running.
Starting vxvault-parser...
vxvault-parser is already running.
Botnet is already running.
[intelmq@nox ~]$ grep ERROR var/log/*
[intelmq@nox ~]$ 
[intelmq@nox ~]$ ./bin/intelmqctl --botnet stop
Stopping Botnet...
Stopping arbor-collector...
Stopping arbor-parser...
cymru-expert was NOT RUNNING.
Stopping deduplicator-expert...
Stopping dragon-research-group-ssh-collector...
Stopping dragon-research-group-ssh-parser...
Stopping dragon-research-group-vnc-collector...
Stopping dragon-research-group-vnc-parser...
Stopping file-output...
Stopping malware-domain-list-collector...
malware-domain-list-parser was NOT RUNNING.
Stopping openbl-collector...
Stopping openbl-parser...
Stopping sanitizer-expert...
Stopping taxonomy-expert...
Stopping vxvault-collector...
Stopping vxvault-parser...
Botnet is stopped.
[intelmq@nox ~]$ ls var/run/
[intelmq@nox ~]$ 
```

So what does that mean in other words and not that long list code dump? 

1. I installed it
2. Then started the botnet, no problems so far
3. I found no errors in the logfiles, if grepping them by ERROR is a sufficient metric for finding them
4. I stopped the botnet, interestingly some bots were not running. And don't know if that is an
    expected behaviour or it means a major breakage.
5. I checked if it stops correctly as it seems, as /opt/intelmq/var/run pidfiles were deleted. As you 
    can see I checked that by a simple ls.

Besides that this pull request also adds *.bak and vim swap files to .gitignore

### CODE REVIEW

**Comment by aaronkaplan** [comment]
I think we Need to take a look at the log files in /opt/intelmq/var/log

Also I believe Tomas is working on a unit testing system. Anyway I d like to review the changes more carefully since they are large! 

---
Mobile

**Comment by Phantasus** [comment]
Agreed, a good test coverage would be a base stone for transitioning.

**Comment by SYNchroACK** [comment]
@Phantasus , send me an email (see my email here https://github.com/certtools/intelmq/blob/master/COPYRIGHT). I would like to discuss some IntelMQ features with you. Thank you very much for your work! :)

**Comment by Phantasus** [comment]
@SYNchroACK Well, I sent you an email. I'm still waiting for your answer.

**Comment by SYNchroACK** [comment]
@Phantasus I believe the pep8 review that you did is really useful in https://github.com/certtools/intelmq-beta

Regarding python 3 check: https://github.com/certtools/intelmq/pull/191

**Comment by sebix** [comment]
As the changes displayed here are very messy, you can use this compare view to see what has been changed: https://github.com/Phantasus/intelmq/compare/master...Phantasus:python3

**Comment by SYNchroACK** [comment]
@sebix I think we should not give priority to this.

**Pull request closed without merging**
