### PR TITLE
FIX: Removed Python 3.6 from CI

### PR DESCRIPTION
**Pull request by kamil-certat**
Our Github Action runners do not have Python 3.6
any more. To unblock building CI, this version
was removed.

This PR is intended to unlock CI. Fully dropping
the Python 3.6 is an another work to do.

### CODE REVIEW

**Comment by waldbauer-certat** [comment]
@sebix Please remove 3.6 as required. Thanks

**Comment by sebix** [comment]
@aaronkaplan Can you please remove the 3.6 tests from the list of required checks (in the settings of the repo)? Only the admin of the repository can do that.

That blocks currently all other PRs as well.

**Review by sebix — APPROVED** [review]
This PR is fine for the CI-part, but 3.6 also needs to be removed on several other places, e.g. setup.py, the docs (user/installation) and explained in NEWS

**Comment by aaronkaplan** [comment]
yup. Tomorrow...

**Review by aaronkaplan — APPROVED** [review]

**Review by aaronkaplan — APPROVED** [review]

**Comment by aaronkaplan** [comment]
> yup. Tomorrow...
> […](#)
> On 07.12.2022, at 21:27, Sebastian ***@***.***> wrote: @aaronkaplan Can you please remove the 3.6 tests from the list of required checks (in the settings of the repo)? Only the admin of the repository can do that. That blocks currently all other PRs as well. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

DONE

**Pull request merged**
