### PR TITLE
Universal shadowserver parser

### LINKED ISSUE #600: shadowserver parser: can't parse open redis feed
```
2016-07-22 18:00:38,243 - openredis-parser - ERROR - Failed to parse line.
Traceback (most recent call last):
  File "/home/aaron/intelmq/intelmq/lib/bot.py", line 461, in process
    events = list(filter(bool, self.parse_line(line, report)))
  File "/home/aaron/intelmq/intelmq/bots/parsers/shadowserver/parser.py", line 182, in parse_line
    event.add('raw', self.recover_line(raw_line))
  File "/home/aaron/intelmq/intelmq/bots/parsers/shadowserver/parser.py", line 198, in recover_line
    out += ','.join(ordered_line) + '\n'
TypeError: sequence item 13: expected str instance, NoneType found
2016-07-22 18:00:38,243 - openredis-parser - INFO - Dumping message from pipeline to dump file.
```

### PR DESCRIPTION
**Pull request by swilde**
Various fixes to the shadowserver parser.
Would close #600, and make more feed work correctly...

This is a updated pull request, merging against current upstream master and fixing even more problems.

### CODE REVIEW

**Comment by aaronkaplan** [comment]
Travis-CI checks complain.

**Comment by sebix** [comment]
I discussed your changes in `recover_line` with @aaronkaplan: We'll merge in your changes.
While it's not the original format, we prefer less LOC until we don't have a better solution to get the original data 1:1. This can be solved in future versions.

> Travis-CI checks complain.

Because the tests are not adapted (`raw` field). When that's done, we'll merge it.

**Comment by sebix** [comment]
And another note @swilde: You don't need to recreate pull requests after pushing some fixes to the source branch of an existing pull request. All commits of the branch are part of the pull request, no matter if they have been created before or after the PR has been opened.

**Comment by swilde** [comment]
I'll update the tests to match the new _raw_-fields.

**Comment by swilde** [comment]
Fixed tests.

**Comment by sebix** [comment]
Merged manually: a12d9cd

**Pull request closed without merging**
