### PR TITLE
Universal csv parser

### PR DESCRIPTION
**Pull request by robcza**
Proposal for a first universal parser, this one for csv inputs. There is a huge space for improvement:
- opportunistic parsing implemented just for time and IP
  - in the time/IP columns try to find the value whatever it takes and use it
  - similar behavior could be implemented for other attributes
  - it could actually be implemented on the lib level (e.g. with ```opportunistic=True``` while adding a value to the event
- other universal parsers could be implemented (json, xml, freetext, etc.)

### CODE REVIEW

**Comment by robcza** [comment]
@sebix you've referred to this type of parser as "generic" instead of "universal" and I liked it. Should I change it to generic? @aaronkaplan

**Comment by aaronkaplan** [comment]
> On 09 Jan 2016, at 19:06, Robert Šefr <notifications@github.com> wrote:
> 
> @sebix you've referred to this type of parser as "generic" instead of "universal" and I liked it. Should I change it to generic? @aaronkaplan
> 
+1

**Comment by sebix** [comment]
* generic is the better term here (use `git mv` to rename the files)
* add an entry in the BOTS file.
* your parser is not compatible to IPv6, but we do want to support it. See also #306 
* Document the features like ignoring comments (`#`) inline and in the BOTS

**Comment by sebix** [comment]
Tests are fine, failures are caused by some changes in DNS/whois.

**Comment by sebix** [comment]
I adapted the code a bit to work with current master, after all my changes :) : https://github.com/sebix/intelmq/commit/75e376679f6a6c8fc3709ada0de6a6a08f69f44e

**Comment by robcza** [comment]
thank you @sebix 
I hope to introduce improvements to this bot step by step, however any proposals are welcome

**Pull request merged**
