### PR TITLE
ESET collector: distribute message sending, no redundant debug messages

### PR DESCRIPTION
**Pull request by monoidic**
Just some small improvements based on feedback in #1554

### CODE REVIEW

**Comment by wagner-certat** [comment]
And then using `event.add('raw', self.recover_line_json_stream())` also fixes the test fails will then use the original message 1:1 (dict key ordering is not consistent in Python)

**Comment by monoidic** [comment]
Iterating over `client.poll` gives a list of dictionaries, otherwise `domains += data` wouldn't have worked previously as concatenating a dict to a list only adds the keys
I suppose maybe giving a list of dicts for the test case might fix it?

**Comment by wagner-certat** [comment]
> Iterating over `client.poll` gives lists of dictionaries, otherwise `domains += data` wouldn't have worked previously as concatenating a dict to a list only adds the keys.

Ah, of course -.-

**Comment by wagner-certat** [comment]
Thanks!

I again did some work based on that: 967e4621f7085da7dd9d9ae1e47ab25a3b898121 As I am unable to test the collector, I hope it still works.

from the commit msg:
> do not save the eset feed in the data anymore but use an extra field
> - collector does not need to interpred, modify and serialize raw data anymore, improves speed and stability (no json errors)
> 
> in parser, add the feed to the event too

**Pull request merged**
