### PR TITLE
Updated scan_amqp and added scan_stun

### PR DESCRIPTION
**Pull request by elsif2**
Updated scan_amqp and added scan_stun.

### CODE REVIEW

**Comment by sebix** [comment]
I think this should go into 3.1.0 and does not require an additional release candidate, as the changes are small.

How do you want to proceed? Do you want to finish the PR yourself (docs, changelog) and merge it yourself directly, or do you prefer to get a code review?

**Comment by elsif2** [comment]
Anything specific you would like for the changelog entry?

Either you or Aaron would need to merge it as I am not authorized.

**Comment by sebix** [comment]
> Anything specific you would like for the changelog entry?

In this case, a short note which feeds were added. You can find a lot of examples there.
```
- `intelmq.bots.parsers.shadowserver._config`:
  - Added support for feeds "AMQP" and "STUN" (PR#2235 by elsif2).
```

Every change (except minor ones) should be documented in the changelog so that the users and developers can see what has changed (relevant for planning and performing an upgrade and next steps)

> Either you or Aaron would need to merge it as I am not authorized.

Ah, OK. My knowledge was, that Aaron authorized you to merge yourself.

**Comment by elsif2** [comment]
Added.  I will include updates to the changelog going forward.

**Review by sebix — APPROVED** [review]

**Comment by sebix** [comment]
Thanks!

**Pull request merged**
